apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liferay
  namespace: liferay
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: liferay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: liferay
                port:
                  number: 8080

