apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-pvc
  namespace: liferay
spec:
  volumeName: liferay-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
