apiVersion: v1
kind: Service
metadata:
  name: liferay-nodeport
  namespace: liferay
spec:
  type: NodePort
  selector:
    app: liferay
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080


